import mongoose from "mongoose";

const userSchema = new mongoose.Schema(
  {
    // 1. Core Identity & Verification
    fullName: {
      type: String,
      required: [true, "OPERATIVE_NAME_REQUIRED"],
      trim: true,
    },
    email: {
      type: String,
      required: [true, "EMAIL_NODE_REQUIRED"],
      unique: true,
      lowercase: true,
      match: [/^\S+@\S+\.\S+$/, "INVALID_UPLINK_NODE"],
    },
    password: {
      type: String,
      required: [true, "SECURITY_KEY_REQUIRED"],
      minlength: 8,
    },
    
    // Distinguishing between Researchers and Enthusiasts
    role: {
      type: String,
      enum: ["enthusiast", "researcher", "admin"],
      default: "enthusiast",
    },

    // Verification status for "Secure Verification" requirement
    isVerified: {
      type: Boolean,
      default: false,
    },

    // 2. Profile Visuals
    profilePhoto: {
      type: String,
      default: "https://api.dicebear.com/7.x/identicon/svg?seed=default",
    },

    // 3. Mission Data (The "Watched" Asteroids)
    watchedAsteroids: [
      {
        neoReferenceId: { type: String, required: true }, // NASA's unique ID
        name: String,
           data: { type: mongoose.Schema.Types.Mixed }, // store full object here
        designation: String,
        riskScore: Number, // Generated by your Risk Analysis Engine
        addedAt: { type: Date, default: Date.now },
      },
    ],

    // 4. Alert System (Custom Alert Parameters)
    alertSettings: {
      minHazardScore: { 
        type: Number, 
        default: 50,
        min: 0,
        max: 100 
      },
      notifyOnCloseApproach: { 
        type: Boolean, 
        default: true 
      },
      alertFrequency: {
        type: String,
        enum: ["instant", "daily", "weekly"],
        default: "instant"
      }
    },

    // 5. System Metadata
    lastLogin: Date,
  },
  { timestamps: true }
);

// Pre-save hook example for password hashing is usually done in the controller,
// but you can add schema methods here for role checks.
userSchema.methods.isResearcher = function() {
  return this.role === 'researcher' || this.role === 'admin';
};

export default mongoose.model("User", userSchema);